"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files:
  - source: amethyst/src/main/res/values/strings.xml
    translation: amethyst/src/main/res/values-%android_code%/%original_file_name%
    type: android
    skip_untranslated_strings: true